sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t uoe326326/React-Gh-Travis -f Dockerfile.dev .

script:
  - docker run -e CI=true uoe326326/React-Gh-Travis npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "React-Gh-Travis"
  env: "React-Gh-Travis-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-730335435582"
  bucket_path: "React-Gh-Travis"
  on:
    branch: master
  access_key_id: $AWS_ACCES_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY